version: "3"
services:
    www_admin:
        build: .
        ports: 
            - "8002:80"
        volumes:
            - ./admin:/var/www/html/
            - ./admin/docker/apache/var/log/apache2:/var/log/apache2
        links:
            - db
        networks:
            - backend
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./:/var/www/html/
            - ./docker/apache/var/log/apache2:/var/log/apache2
        links:
            - db
        networks:
            - db_network
            - frontend
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - db_network
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - backend
volumes:
    persistent:
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
    db_network:
        driver: bridge
